# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.1
neo_version=21.1.219
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_group=com.shynieke.georenouveau
mod_id=georenouveau
mod_archive_name=GeOre_Nouveau

#Publishing
mod_name=GeOre Nouveau
curseforge_id=667803
modrinth_id=wxufWCS4

# Version
version=0.5.8

# Dependencies
jei_version=19.27.0.340
geore_version=6.2.2
patchouli_version=1.21.1-92-NEOFORGE
caelus_version=7.0.1+1.21.1
ars_version=5.11.2.+
gecko_version=4.8.3
curios_version=9.5.1+1.21.1