modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/GeoreNouveau/issues"
license="GNU LGPL v3"

[[mods]]
modId="georenouveau"
version="${file.jarVersion}"
displayName="GeOre Nouveau"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geore-nouveau"
authors="Mrbysco, ShyNieke"
description='''
Small addon mod for GeOre and Ars Nouveau
'''
[[dependencies.georenouveau]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.georenouveau]]
modId="forge"
mandatory=true
versionRange="[47.0.35,)"
ordering="NONE"
side="BOTH"
[[dependencies.georenouveau]]
modId="geore"
mandatory=true
versionRange="[2.4.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.georenouveau]]
modId="ars_nouveau"
mandatory=true
versionRange="[4.2.0,)"
ordering="AFTER"
side="BOTH"