modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/GeoreNouveau/issues"
license="GNU LGPL v3"

[[mods]]
modId="georenouveau"
version="${file.jarVersion}"
displayName="GeOre Nouveau"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geore-nouveau"
authors="Mrbysco, ShyNieke"
description='''
Small addon mod for GeOre and Ars Nouveau
'''
[[dependencies.georenouveau]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.georenouveau]]
modId="neoforge"
type="required"
versionRange="[21.0.110-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.georenouveau]]
modId="geore"
type="required"
versionRange="[6.0.4,)"
ordering="AFTER"
side="BOTH"
[[dependencies.georenouveau]]
modId="ars_nouveau"
type="required"
versionRange="[5.2.1,)"
ordering="AFTER"
side="BOTH"
[[mixins]]
config="georenouveau.mixins.json"